# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        LIBS += -lbbplatformbbm

        SOURCES +=  $$quote($$BASEDIR/src/SurfingSADev.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItemFactory.cpp) \
                 $$quote($$BASEDIR/src/functionality/Album.cpp) \
                 $$quote($$BASEDIR/src/functionality/AlbumView.cpp) \
                 $$quote($$BASEDIR/src/functionality/Auction.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionCategories.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionCreate.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionInfo.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionList.cpp) \
                 $$quote($$BASEDIR/src/functionality/Booster.cpp) \
                 $$quote($$BASEDIR/src/functionality/Card.cpp) \
                 $$quote($$BASEDIR/src/functionality/Credits.cpp) \
                 $$quote($$BASEDIR/src/functionality/Friends.cpp) \
                 $$quote($$BASEDIR/src/functionality/ImageLoader.cpp) \
                 $$quote($$BASEDIR/src/functionality/InviteFriend.cpp) \
                 $$quote($$BASEDIR/src/functionality/Login.cpp) \
                 $$quote($$BASEDIR/src/functionality/Notifications.cpp) \
                 $$quote($$BASEDIR/src/functionality/OnAuctionList.cpp) \
                 $$quote($$BASEDIR/src/functionality/Purchase.cpp) \
                 $$quote($$BASEDIR/src/functionality/Redeem.cpp) \
                 $$quote($$BASEDIR/src/functionality/Registration.cpp) \
                 $$quote($$BASEDIR/src/functionality/Shop.cpp) \
                 $$quote($$BASEDIR/src/functionality/Weather.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/utils/Util.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/SurfingSADev.hpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItemFactory.h) \
                 $$quote($$BASEDIR/src/functionality/Album.h) \
                 $$quote($$BASEDIR/src/functionality/AlbumView.h) \
                 $$quote($$BASEDIR/src/functionality/Auction.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionCategories.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionCreate.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionInfo.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionList.h) \
                 $$quote($$BASEDIR/src/functionality/Booster.h) \
                 $$quote($$BASEDIR/src/functionality/Card.h) \
                 $$quote($$BASEDIR/src/functionality/Credits.h) \
                 $$quote($$BASEDIR/src/functionality/Friends.h) \
                 $$quote($$BASEDIR/src/functionality/ImageLoader.h) \
                 $$quote($$BASEDIR/src/functionality/InviteFriend.h) \
                 $$quote($$BASEDIR/src/functionality/Login.h) \
                 $$quote($$BASEDIR/src/functionality/Notifications.h) \
                 $$quote($$BASEDIR/src/functionality/OnAuctionList.h) \
                 $$quote($$BASEDIR/src/functionality/Purchase.h) \
                 $$quote($$BASEDIR/src/functionality/Redeem.h) \
                 $$quote($$BASEDIR/src/functionality/Registration.h) \
                 $$quote($$BASEDIR/src/functionality/Shop.h) \
                 $$quote($$BASEDIR/src/functionality/Weather.h) \
                 $$quote($$BASEDIR/src/utils/Util.h)

    }

    CONFIG(release, debug|release) {
        LIBS += -lbbplatformbbm

        SOURCES +=  $$quote($$BASEDIR/src/SurfingSADev.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItemFactory.cpp) \
                 $$quote($$BASEDIR/src/functionality/Album.cpp) \
                 $$quote($$BASEDIR/src/functionality/AlbumView.cpp) \
                 $$quote($$BASEDIR/src/functionality/Auction.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionCategories.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionCreate.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionInfo.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionList.cpp) \
                 $$quote($$BASEDIR/src/functionality/Booster.cpp) \
                 $$quote($$BASEDIR/src/functionality/Card.cpp) \
                 $$quote($$BASEDIR/src/functionality/Credits.cpp) \
                 $$quote($$BASEDIR/src/functionality/Friends.cpp) \
                 $$quote($$BASEDIR/src/functionality/ImageLoader.cpp) \
                 $$quote($$BASEDIR/src/functionality/InviteFriend.cpp) \
                 $$quote($$BASEDIR/src/functionality/Login.cpp) \
                 $$quote($$BASEDIR/src/functionality/Notifications.cpp) \
                 $$quote($$BASEDIR/src/functionality/OnAuctionList.cpp) \
                 $$quote($$BASEDIR/src/functionality/Purchase.cpp) \
                 $$quote($$BASEDIR/src/functionality/Redeem.cpp) \
                 $$quote($$BASEDIR/src/functionality/Registration.cpp) \
                 $$quote($$BASEDIR/src/functionality/Shop.cpp) \
                 $$quote($$BASEDIR/src/functionality/Weather.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/utils/Util.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/SurfingSADev.hpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItemFactory.h) \
                 $$quote($$BASEDIR/src/functionality/Album.h) \
                 $$quote($$BASEDIR/src/functionality/AlbumView.h) \
                 $$quote($$BASEDIR/src/functionality/Auction.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionCategories.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionCreate.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionInfo.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionList.h) \
                 $$quote($$BASEDIR/src/functionality/Booster.h) \
                 $$quote($$BASEDIR/src/functionality/Card.h) \
                 $$quote($$BASEDIR/src/functionality/Credits.h) \
                 $$quote($$BASEDIR/src/functionality/Friends.h) \
                 $$quote($$BASEDIR/src/functionality/ImageLoader.h) \
                 $$quote($$BASEDIR/src/functionality/InviteFriend.h) \
                 $$quote($$BASEDIR/src/functionality/Login.h) \
                 $$quote($$BASEDIR/src/functionality/Notifications.h) \
                 $$quote($$BASEDIR/src/functionality/OnAuctionList.h) \
                 $$quote($$BASEDIR/src/functionality/Purchase.h) \
                 $$quote($$BASEDIR/src/functionality/Redeem.h) \
                 $$quote($$BASEDIR/src/functionality/Registration.h) \
                 $$quote($$BASEDIR/src/functionality/Shop.h) \
                 $$quote($$BASEDIR/src/functionality/Weather.h) \
                 $$quote($$BASEDIR/src/utils/Util.h)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        LIBS += -lbbplatformbbm

        SOURCES +=  $$quote($$BASEDIR/src/SurfingSADev.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItemFactory.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItem.cpp) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItemFactory.cpp) \
                 $$quote($$BASEDIR/src/functionality/Album.cpp) \
                 $$quote($$BASEDIR/src/functionality/AlbumView.cpp) \
                 $$quote($$BASEDIR/src/functionality/Auction.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionCategories.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionCreate.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionInfo.cpp) \
                 $$quote($$BASEDIR/src/functionality/AuctionList.cpp) \
                 $$quote($$BASEDIR/src/functionality/Booster.cpp) \
                 $$quote($$BASEDIR/src/functionality/Card.cpp) \
                 $$quote($$BASEDIR/src/functionality/Credits.cpp) \
                 $$quote($$BASEDIR/src/functionality/Friends.cpp) \
                 $$quote($$BASEDIR/src/functionality/ImageLoader.cpp) \
                 $$quote($$BASEDIR/src/functionality/InviteFriend.cpp) \
                 $$quote($$BASEDIR/src/functionality/Login.cpp) \
                 $$quote($$BASEDIR/src/functionality/Notifications.cpp) \
                 $$quote($$BASEDIR/src/functionality/OnAuctionList.cpp) \
                 $$quote($$BASEDIR/src/functionality/Purchase.cpp) \
                 $$quote($$BASEDIR/src/functionality/Redeem.cpp) \
                 $$quote($$BASEDIR/src/functionality/Registration.cpp) \
                 $$quote($$BASEDIR/src/functionality/Shop.cpp) \
                 $$quote($$BASEDIR/src/functionality/Weather.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/utils/Util.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/SurfingSADev.hpp) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/AlbumItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/AuctionItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/ShopItemFactory.h) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItem.h) \
                 $$quote($$BASEDIR/src/customcomponents/WeatherItemFactory.h) \
                 $$quote($$BASEDIR/src/functionality/Album.h) \
                 $$quote($$BASEDIR/src/functionality/AlbumView.h) \
                 $$quote($$BASEDIR/src/functionality/Auction.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionCategories.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionCreate.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionInfo.h) \
                 $$quote($$BASEDIR/src/functionality/AuctionList.h) \
                 $$quote($$BASEDIR/src/functionality/Booster.h) \
                 $$quote($$BASEDIR/src/functionality/Card.h) \
                 $$quote($$BASEDIR/src/functionality/Credits.h) \
                 $$quote($$BASEDIR/src/functionality/Friends.h) \
                 $$quote($$BASEDIR/src/functionality/ImageLoader.h) \
                 $$quote($$BASEDIR/src/functionality/InviteFriend.h) \
                 $$quote($$BASEDIR/src/functionality/Login.h) \
                 $$quote($$BASEDIR/src/functionality/Notifications.h) \
                 $$quote($$BASEDIR/src/functionality/OnAuctionList.h) \
                 $$quote($$BASEDIR/src/functionality/Purchase.h) \
                 $$quote($$BASEDIR/src/functionality/Redeem.h) \
                 $$quote($$BASEDIR/src/functionality/Registration.h) \
                 $$quote($$BASEDIR/src/functionality/Shop.h) \
                 $$quote($$BASEDIR/src/functionality/Weather.h) \
                 $$quote($$BASEDIR/src/utils/Util.h)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/functionality) \
         $$quote($$BASEDIR/src/customcomponents) \
         $$quote($$BASEDIR/src/utils) \
         $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}.ts)

